### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by tekoscott** [nathanwoulfe/Flip#4]
Hi Nathan,

Not sure wether its me or an issue but will explain my situation.

I am using Umbraco 12

I have a listpage as a content node, this list consists of a series of document nodes. 

I am trying to change the listed document nodes from one document type to another. The only difference between the two document types is that one contains a date field and another does not. I am trying to use 'Flip' to change doctypes to the one with the date.  I don't want to add the new property to the existing doctype as this is used elsewhere.

I can't seem to find the context menu that will allow me to do this.

Are you able to provide some insight.

Kind Regards
Scott

**Comment by nathanwoulfe** [comment]
Hey Scott, hopefully this is as straightforward as updating the permissions for the user/group. Flip adds a new permission to hopefully limit the amount of damage people can do 🙄

**Comment by tekoscott** [comment]
Hey Nathan,

Thanks for that. After I enabled permission and turned of list I could access each content node and change the doctype.

Regards

Scott
